export default {
  login: "keddy406",
  id: 54757799,
  node_id: "MDQ6VXNlcjU0NzU3Nzk5",
  avatar_url: "https://avatars2.githubusercontent.com/u/54757799?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/keddy406",
  html_url: "https://github.com/keddy406",
  followers_url: "https://api.github.com/users/keddy406/followers",
  following_url: "https://api.github.com/users/keddy406/following{/other_user}",
  gists_url: "https://api.github.com/users/keddy406/gists{/gist_id}",
  starred_url: "https://api.github.com/users/keddy406/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/keddy406/subscriptions",
  organizations_url: "https://api.github.com/users/keddy406/orgs",
  repos_url: "https://api.github.com/users/keddy406/repos",
  events_url: "https://api.github.com/users/keddy406/events{/privacy}",
  received_events_url: "https://api.github.com/users/keddy406/received_events",
  type: "User",
  site_admin: false,
  name: "Chunyuan",
  company: "KC-company",
  blog: "kc-mainportfolio.netlify.app",
  location: "kaohsiung",
  email: null,
  hireable: null,
  bio: "Take control of your own desting.\r\n    \r\n",
  twitter_username: "twkccy1990",
  public_repos: 33,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-09-01T02:08:54Z",
  updated_at: "2020-07-20T07:16:08Z",
};
